services:
  backend:
    image: groben5558/alfri:alfri-backend
    container_name: alfri_be
    environment:
      PROD_SHOW_SQL: ${PROD_SHOW_SQL}
      DATABASE_PROD_PASSWORD: ${DATABASE_PROD_PASSWORD}
      FRONTEND_PROD_URL: ${FRONTEND_PROD_URL}
      DATABASE_PROD_USER: ${DATABASE_PROD_USER}
      DATABASE_PROD_URL: ${DATABASE_PROD_URL}
      JWT_PROD_EXPIRATION_TIME: ${JWT_PROD_EXPIRATION_TIME}
      JWT_PROD_SECRET_KEY: ${JWT_PROD_SECRET_KEY}
      APPLICATION_NAME: ${APPLICATION_NAME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    build:
      context: ./BE
    ports:
      - "8080:8080"
  frontend:
    image: groben5558/alfri:alfri-frontend
    container_name: alfri_fe
    build:
      context: ./FE
    ports:
      - "80:80"
    depends_on:
      - backend