FROM maven:3.9.6-sapmachine-21 AS provider-build
WORKDIR /build

COPY docker/keycloak/event-listener/pom.xml ./pom.xml
RUN mvn -B -DskipTests dependency:go-offline

COPY docker/keycloak/event-listener /build
RUN mvn -B -DskipTests package

FROM quay.io/keycloak/keycloak:26.6.2 AS builder

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_ENABLED=true
ENV KC_PROXY_HEADERS=xforwarded

COPY --from=provider-build --chown=keycloak:keycloak /build/target/alfri-keycloak-event-listener-*.jar /opt/keycloak/providers/
COPY --chown=keycloak:keycloak docker/keycloak/themes/ /opt/keycloak/themes/
COPY --chown=keycloak:keycloak docker/keycloak/import-azure-dev/ /opt/keycloak/data/import/

RUN touch -m --date=@1743465600 /opt/keycloak/providers/*
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.6.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY --chown=keycloak:keycloak docker/keycloak/entrypoint.sh /opt/keycloak/bin/entrypoint.sh
USER root
RUN chmod +x /opt/keycloak/bin/entrypoint.sh
USER keycloak
ENTRYPOINT ["/opt/keycloak/bin/entrypoint.sh"]
