spring:
  config:
    import: optional:file:BE/src/main/resources/.env[.properties],optional:file:../.env[.properties]
  application:
    name: ${APPLICATION_NAME:ALFRI_BE}
  datasource:
    url: ${DATABASE_PROD_URL:jdbc:postgresql://alfri-database.postgres.database.azure.com:5432/alfri}
    username: ${DATABASE_PROD_USER}
    password: ${DATABASE_PROD_PASSWORD}
  jpa:
    show-sql: ${PROD_SHOW_SQL}
    hibernate:
      # Spring Boot won't modify the database based on @Entity classes - we must update the database ourselves
      ddl-auto: none
  security:
    jwt:
      secret-key: ${JWT_PROD_SECRET_KEY}
      expiration-time: ${JWT_PROD_EXPIRATION_TIME}
frontend-url: ${FRONTEND_PROD_URL}
