spring:
  application:
    name: ${APPLICATION_NAME:alfri}
  datasource:
    url: jdbc:postgresql://${DATABASE_PROD_URL:localhost:5432/alfri}
    username: ${DATABASE_PROD_USER:alfri_be}
    password: ${DATABASE_PROD_PASSWORD:password123}
    driver-class-name: ${DATABASE_PROD_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: ${PROD_SHOW_SQL:false}
    hibernate:
      # Spring Boot won't modify the database based on @Entity classes - we must update the database ourselves
      ddl-auto: none
  security:
    jwt:
      secret-key: ${JWT_PROD_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expiration-time: ${JWT_PROD_EXPIRATION_TIME:3600000}
frontend-url: ${FRONTEND_PROD_URL:http://localhost:4200}
