spring:
  application:
    name: ${APPLICATION_NAME:ALFRI_BE}
  datasource:
    url: jdbc:postgresql://${DATABASE_DEV_URL:localhost:5432/alfri}
    username: ${DATABASE_DEV_USER:alfri_be}
    password: ${DATABASE_DEV_PASSWORD:password123}
  jpa:
    show-sql: ${DEV_SHOW_SQL:false}
    hibernate:
      # Spring Boot won't modify the database based on @Entity classes - we must update the database ourselves
      ddl-auto: none
  security:
    jwt:
      secret-key: ${JWT_DEV_SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
      expiration-time: ${JWT_DEV_EXPIRATION_TIME:3600000}

python:
  executable_path: ${PYTHON_DEV_EXECUTABLE_PATH:python3}
  clustering_prediction_script_path: ${DEV_CLUSTERING_PREDICTION_SCRIPT_PATH:/app/python_scripts/subject_clustering.py}
  clustering_prediction_model_path: ${DEV_CLUSTERING_PREDICTION_MODEL_PATH:/app/python_scripts/kmeans_model.pkl}
  passing_change_prediction_script_path: ${DEV_PASSING_CHANGE_PREDICTION_SCRIPT_PATH:/app/python_scripts/passing_chance_prediction.py}
  passing_mark_prediction_script_path: ${DEV_PASSING_MARK_PREDICTION_SCRIPT_PATH:/app/python_scripts/neural_network_marks_predictions.py}



frontend-url: ${FRONTEND_DEV_URL:*}
# email of user that you want to act as
default-user-email: szathmary@stud.uniza.sk
# roles that you want to have - upper case with comma in between them
default-user-roles: STUDENT, TEACHER, VISITOR, ADMIN
