name: Java CI with Maven

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Ensure token is passed to checkout action

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build Backend with Maven
      run: |
        cd BE
        mvn -B package --file pom.xml

    - name: Run Spotless check and apply formatting
      run: |
        cd BE
        mvn spotless:apply

    - name: Check for formatting changes
      run: |
        cd BE
        git diff --exit-code || echo "Spotless applied formatting changes."

    - name: Commit and push formatting changes
      if: ${{ always() }}
      run: |
        cd BE
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add .
        git commit -m "Apply code formatting with Spotless" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.head_ref || github.ref_name }}
